### ISSUE TITLE
Add Movie#tick,play

### ISSUE THREAD

**Issue by clabe45** [ved-editor/ved#12]
- [ ] `tick` updates all the nodes in a movie by calling each one.
- [ ] `play` calls `tick` periodically in a given time interval (so it's just used for updating nodes).
- `export` (now `record`) calls `tick` periodically *and* accumulates the result into one video file (see #17)

*Note that the user can also call `tick` if they need to.*

**Comment by BoLiu97** [comment]
bo -_-

**Comment by clabe45** [comment]
Bo said he can no longer be involved with this project, so this issue is open
